version: "2"

linters:
  default: standard
  enable:
    - copyloopvar
    - dupword
    - durationcheck
    - errorlint
    - gocritic
    - intrange
    - misspell
    - unconvert
    - unparam
    - usestdlibvars

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - unparam

formatters:
  enable:
    - goimports

run:
  timeout: 5m
